var upgradeID = new Array( // REALLY LONG ARRAY THAT USED TO BE SEPERATED INTO MULTIPLE ARRAYS... This just looks cleaner...
			// [0]UpgradeID, [1]UpgradeName, [2]Cost, [3]Function, [4]Added, [5]Bought, [6]Requirements // I really wish there was an easier way to set the requirements... -ragagagage-
	new Array("semiNameUpgrade", "LI", 5, firstNameUpgrade, false, false, "C5;"),
	new Array("properNameUpgrade", "%names%", 10, finalNameUpgrade, false, false, "M10;UsemiNameUpgrade;"),
	new Array("moneyDisplay", "%display%", 10, displayMoney, false, false, "M10;UsemiNameUpgrade;"),
	new Array("upgradeBox", "Upgrade Box", 20, upgradeBox, false, false, "M20;UproperNameUpgrade;"),
	new Array("titleFix", "Fix Title", 50, titleFix, false, false, "M50;UproperNameUpgrade;"),
	new Array("titleCounter", "Title Counter", 150, titleCounter, false, false, "M150;UmoneyDisplay,titleFix;"),
	new Array("upgradeCostDisplay", "Cost Display", 50, costDisplay, false, false, "UmoneyDisplay,upgradeBox;"),
	new Array("statsWindow", "Statistics Window", 75, simpleStatWindow, false, false, "M75;UmoneyDisplay,upgradeBox;"),
	new Array("upgradeStatsWindow", "Statistics Window Upgrade", 375, upgradeStatWindow, false, false, "UstatsWindow;"),
	new Array("statsUpgrade", "Upgrade Statistics", 150, statsUpgrade, false, false, "UstatsWindow;"),
	new Array("statsAutomations", "Automation Statistics", 150, statsAutomations, false, false, "A1=automation-basic;"),
	new Array("tickerFixer", "Fix Ticker", 250, tickerFixer, false, false, "M250;UproperNameUpgrade;"),
	new Array("tickerRealInfo", "Ticker News", 475, tickerRealInfo, false, false, "UtickerFixer;"),
	new Array("automationBox", "Automation Display", 750, simpleAutomationBox, false, false, "UupgradeStatsWindow;"),
	new Array("upgradeAutomationUI", "Automation Display", 200, automationUIUp, false, false, "UautomationBox;"),
	new Array("saveManagerUI", "Save Manager", 500, saveManagerUI, false, false, "UupgradeStatsWindow;"),
	new Array("upgradeClicks1", "Click Upgrade", 100, upgradeMouse("upgradeClicks1", 1), false, false, "C150;UproperNameUpgrade;"),
	new Array("upgradeClicks2", "Basic Click Upgrade", 200, upgradeMouse("upgradeClicks2", 2), false, false, "C500;A1=automation-basic;UupgradeClicks1;"),
	new Array("upgradeClicks3", "Novice Click Upgrade", 600, upgradeMouse("upgradeClicks3", 4), false, false, "C1000;A1=automation-novice;UupgradeClicks2;"),
	new Array("upgradeClicks4", "Intermediate Click Upgrade", 1200, upgradeMouse("upgradeClicks4", 8), false, false, "C1500;A1=automation-intermediate;UupgradeClicks3;"),
	new Array("upgradeClicks5", "Advanced Click Upgrade", 2400, upgradeMouse("upgradeClicks5", 16), false, false, "C2000;A1=automation-advanced;UupgradeClicks4;"),
	new Array("upgradeClicks6", "Expert Click Upgrade", 4800, upgradeMouse("upgradeClicks6", 32), false, false, "C2500;A1=automation-expert;UupgradeClicks5;"),
	new Array("upgradeClicks7", "Homeless Clicker", 9000, upgradeClickMPC("upgradeClicks7", .02), false, false, "C3000;UupgradeClicks6;"),
	new Array("upgradeClicks8", "Poor Clicker", 18000, upgradeClickMPC("upgradeClicks8", .02), false, false, "C3500;UupgradeClicks7;"),
	new Array("upgradeClicks9", "Lower Class Clicker", 36000, upgradeClickMPC("upgradeClicks9", .02), false, false, "C4000;UupgradeClicks8;"),
	new Array("upgradeClicks10", "Middle Class Clicker", 72000, upgradeClickMPC("upgradeClicks10", .02), false, false, "C4500;UupgradeClicks9;"),
	new Array("upgradeClicks11", "Upper Class Clicker", 144000, upgradeClickMPC("upgradeClicks11", .02), false, false, "C5000;UupgradeClicks10;"),
	new Array("upgradeClicks12", "Rich Clicker", 288000, upgradeClickMPC("upgradeClicks12", .02), false, false, "C5500;UupgradeClicks11;"),
	new Array("upgradeClicks13", "Thirteen", 576000, upgradeClickMPC("upgradeClicks13", .02), false, false, "C6000;UupgradeClicks12;"),
	new Array("upgradeClicks14", "Tycoon Clicker", 1500000, upgradeClickMPC("upgradeClicks14", .06), false, false, "C6500;UupgradeClicks13;"),
	new Array("upgradeSaveUI", "Save Manager Display", 150, saveManagerUIUp, false, false, "UsaveManagerUI;"),
	new Array("automationUpgrades", "Automation Upgrades", 500, automationUpgrades, false, false, "A10=automation-basic;UunlockBasicAutomation;"),
	new Array("unlockBasicAutomation", "Basic Automation", 250, unlockAutomation("unlockBasicAutomation", "automation-basic"), false, false, "UautomationBox;"),
	new Array("unlockNoviceAutomation", "Novice Automation", 500, unlockAutomation("unlockNoviceAutomation", "automation-novice"), false, false, "A5=automation-basic;"),
	new Array("unlockIntermediateAutomation", "Intermediate Automation", 1000, unlockAutomation("unlockIntermediateAutomation", "automation-intermediate"), false, false, "A5=automation-novice;"),
	new Array("unlockAdvancedAutomation", "Advanced Automation", 2000, unlockAutomation("unlockAdvancedAutomation", "automation-advanced"), false, false, "A5=automation-intermediate;"),
	new Array("unlockExpertAutomation", "Expert Automation", 4000, unlockAutomation("unlockExpertAutomation", "automation-expert"), false, false, "A5=automation-advanced;"),
	new Array("basicAutomationU1", "Basic Basic Automation Upgrade", 125, upgradeAutomation("basicAutomationU1", "automation-basic", 0.5), false, false, "A10=automation-basic;UautomationUpgrades;"),
	new Array("basicAutomationU2", "Novice Basic Automation Upgrade", 500, upgradeAutomation("basicAutomationU2", "automation-basic", 1), false, false, "A1=automation-novice,20=automation-basic;UbasicAutomationU1;"),
	new Array("basicAutomationU3", "Intermediate Basic Automation Upgrade", 1500, upgradeAutomation("basicAutomationU3", "automation-basic", 2), false, false, "A1=automation-intermediate,30=automation-basic;UbasicAutomationU2;"),
	new Array("basicAutomationU4", "Advanced Basic Automation Upgrade", 4500, upgradeAutomation("basicAutomationU4", "automation-basic", 8), false, false, "A1=automation-advanced,40=automation-basic;UbasicAutomationU3;"),
	new Array("basicAutomationU5", "Expert Basic Automation Upgrade", 13500, upgradeAutomation("basicAutomationU5", "automation-basic", 32), false, false, "A1=automation-expert,50=automation-basic;UbasicAutomationU4;"),
	new Array("upgradeMPCU1", "Basic MPC Upgrade", 1000000, upgradeClickMPC("upgradeMPCU1", .05), false, false, "UbasicAutomationU5;"),
	new Array("noviceAutomationU1", "Basic Novice Automation Upgrade", 250, upgradeAutomation("noviceAutomationU1", "automation-novice", 2.5), false, false, "A10=automation-novice;UautomationUpgrades;"),
	new Array("noviceAutomationU2", "Novice Novice Automation Upgrade", 1000, upgradeAutomation("noviceAutomationU2", "automation-novice", 5), false, false, "A20=automation-novice;UnoviceAutomationU1;"),
	new Array("noviceAutomationU3", "Intermediate Novice Automation Upgrade", 3000, upgradeAutomation("noviceAutomationU3", "automation-novice", 10), false, false, "A1=automation-intermediate,30=automation-novice;UnoviceAutomationU2;"),
	new Array("noviceAutomationU4", "Advanced Novice Automation Upgrade", 9000, upgradeAutomation("noviceAutomationU4", "automation-novice", 40), false, false, "A1=automation-advanced,40=automation-novice;UnoviceAutomationU3;"),
	new Array("noviceAutomationU5", "Expert Novice Automation Upgrade", 27000, upgradeAutomation("noviceAutomationU5", "automation-novice", 160), false, false, "A1=automation-expert,50=automation-novice;UnoviceAutomationU4;"),
	new Array("upgradeMPCU2", "Novice MPC Upgrade", 2000000, upgradeClickMPC("upgradeMPCU2", .05), false, false, "UnoviceAutomationU5,upgradeMPCU1;"),
	new Array("intermediateAutomationU1", "Basic Intermediate Automation Upgrade", 500, upgradeAutomation("intermediateAutomationU1", "automation-intermediate", 5), false, false, "A10=automation-intermediate;UautomationUpgrades;"),
	new Array("intermediateAutomationU2", "Novice Intermediate Automation Upgrade", 2000, upgradeAutomation("intermediateAutomationU2", "automation-intermediate", 10), false, false, "A1=automation-novice,20=automation-intermediate;UintermediateAutomationU1;"),
	new Array("intermediateAutomationU3", "Intermediate Intermediate Automation Upgrade", 6000, upgradeAutomation("intermediateAutomationU3", "automation-intermediate", 20), false, false, "A30=automation-intermediate;UintermediateAutomationU2;"),
	new Array("intermediateAutomationU4", "Advanced Intermediate Automation Upgrade", 18000, upgradeAutomation("intermediateAutomationU4", "automation-intermediate", 80), false, false, "A1=automation-advanced,40=automation-intermediate;UintermediateAutomationU3;"),
	new Array("intermediateAutomationU5", "Expert Intermediate Automation Upgrade", 54000, upgradeAutomation("intermediateAutomationU5", "automation-intermediate", 320), false, false, "A1=automation-expert,50=automation-intermediate;UintermediateAutomationU4;"),
	new Array("upgradeMPCU3", "Intermediate MPC Upgrade", 3000000, upgradeClickMPC("upgradeMPCU3", .05), false, false, "UintermediateAutomationU5,upgradeMPCU2;"),
	new Array("advancedAutomationU1", "Basic Advanced Automation Upgrade", 1000, upgradeAutomation("advancedAutomationU1", "automation-advanced", 12.5), false, false, "A10=automation-advanced;UautomationUpgrades;"),
	new Array("advancedAutomationU2", "Novice Advanced Automation Upgrade", 4000, upgradeAutomation("advancedAutomationU2", "automation-advanced", 25), false, false, "A1=automation-novice,20=automation-advanced;UadvancedAutomationU1;"),
	new Array("advancedAutomationU3", "Intermediate Advanced Automation Upgrade", 12000, upgradeAutomation("advancedAutomationU3", "automation-advanced", 50), false, false, "A1=automation-intermediate,30=automation-advanced;UadvancedAutomationU2;"),
	new Array("advancedAutomationU4", "Advanced Advanced Automation Upgrade", 36000, upgradeAutomation("advancedAutomationU4", "automation-advanced", 200), false, false, "A40=automation-advanced;UadvancedAutomationU3;"),
	new Array("advancedAutomationU5", "Expert Advanced Automation Upgrade", 108000, upgradeAutomation("advancedAutomationU5", "automation-advanced", 800), false, false, "A1=automation-expert,50=automation-advanced;UadvancedAutomationU4;"),
	new Array("upgradeMPCU4", "Advanced MPC Upgrade", 4000000, upgradeClickMPC("upgradeMPCU4", .05), false, false, "UadvancedAutomationU5,upgradeMPCU3;"),
	new Array("expertAutomationU1", "Basic Expert Automation Upgrade", 2000, upgradeAutomation("expertAutomationU1", "automation-expert", 25), false, false, "A10=automation-expert;UautomationUpgrades;"),
	new Array("expertAutomationU2", "Novice Expert Automation Upgrade", 8000, upgradeAutomation("expertAutomationU2", "automation-expert", 50), false, false, "A1=automation-novice,20=automation-expert;UexpertAutomationU1;"),
	new Array("expertAutomationU3", "Intermediate Expert Automation Upgrade", 24000, upgradeAutomation("expertAutomationU3", "automation-expert", 100), false, false, "A1=automation-intermediate,30=automation-expert;UexpertAutomationU2;"),
	new Array("expertAutomationU4", "Advanced Expert Automation Upgrade", 72000, upgradeAutomation("expertAutomationU4", "automation-expert", 400), false, false, "A1=automation-advanced,40=automation-expert;UexpertAutomationU3;"),
	new Array("expertAutomationU5", "Expert Expert Automation Upgrade", 216000, upgradeAutomation("expertAutomationU5", "automation-expert", 2000), false, false, "A50=automation-expert;UexpertAutomationU4;"),
	new Array("upgradeMPCU5", "Expert MPC Upgrade", 5000000, upgradeClickMPC("upgradeMPCU5", .10), false, false, "UexpertAutomationU5,upgradeMPCU4;"),
	new Array("domainSystemU1", "Basic Domain System", 100000000, domainSystem, false, false, "UbasicAutomationU5,noviceAutomationU5,intermediateAutomationU5,advancedAutomationU5,expertAutomationU5;"),
	new Array("bounceCPSU1", "Balancing", 500000000, upgradeBounceCPS("bounceCPSU1", 1), false, false, "C10000;UdomainSystemU1;"),
	new Array("basicDomain", "Basic Domain", 10000000, startDomain("basicDomain", "automation-basic", 10, 1.25), false, false, "UdomainSystemU1;"),
	new Array("noviceDomain", "Novice Domain", 30000000, startDomain("noviceDomain", "automation-novice", 25, 1.25), false, false, "UdomainSystemU1;"),
	new Array("intermediateDomain", "Intermediate Domain", 50000000, startDomain("intermediateDomain", "automation-intermediate", 50, 1.25), false, false, "UdomainSystemU1;"),
	new Array("advancedDomain", "Advanced Domain", 70000000, startDomain("advancedDomain", "automation-advanced", 100, 1.25), false, false, "UdomainSystemU1;"),
	new Array("expertDomain", "Expert Domain", 90000000, startDomain("expertDomain", "automation-expert", 200, 1.25), false, false, "UdomainSystemU1;"),
	new Array("basicDomainU1", "Basic Hostile Upgrade", 5000000, multiplyAutomationIncome("basicDomainU1", "automation-basic", 2), false, false, "A1=automation-basic;UbasicDomain;"),
	new Array("basicDomainU2", "Basic Angered Upgrade", 7500000, multiplyAutomationIncome("basicDomainU2", "automation-basic", 3), false, false, "A10=automation-basic;UbasicDomainU1;"),
	new Array("basicDomainU3", "Basic Wary Upgrade", 10000000, multiplyAutomationIncome("basicDomainU3", "automation-basic", 4), false, false, "A25=automation-basic;UbasicDomainU2;"),
	new Array("basicDomainU4", "Basic Neutral Upgrade", 12500000, multiplyAutomationIncome("basicDomainU4", "automation-basic", 5), false, false, "A50=automation-basic;UbasicDomainU3;"),
	new Array("basicDomainU5", "Basic Friendly Upgrade", 15000000, multiplyAutomationIncome("basicDomainU5", "automation-basic", 6), false, false, "A75=automation-basic;UbasicDomainU4;"),
	new Array("basicDomainU6", "Basic Respected Upgrade", 17500000, multiplyAutomationIncome("basicDomainU6", "automation-basic", 7), false, false, "A100=automation-basic;UbasicDomainU5;"),
	new Array("basicDomainU7", "Basic Honoured Upgrade", 40000000, multiplyAutomationIncome("basicDomainU7", "automation-basic", 10), false, false, "A150=automation-basic;UbasicDomainU6;"),
	new Array("noviceDomainU1", "Novice Hostile Upgrade", 7500000, multiplyAutomationIncome("noviceDomainU1", "automation-novice", 2), false, false, "A1=automation-novice;UnoviceDomain;"),
	new Array("noviceDomainU2", "Novice Angered Upgrade", 10000000, multiplyAutomationIncome("noviceDomainU2", "automation-novice", 3), false, false, "A10=automation-novice;UnoviceDomainU1;"),
	new Array("noviceDomainU3", "Novice Wary Upgrade", 12500000, multiplyAutomationIncome("noviceDomainU3", "automation-novice", 4), false, false, "A25=automation-novice;UnoviceDomainU2;"),
	new Array("noviceDomainU4", "Novice Neutral Upgrade", 15000000, multiplyAutomationIncome("noviceDomainU4", "automation-novice", 5), false, false, "A50=automation-novice;UnoviceDomainU3;"),
	new Array("noviceDomainU5", "Novice Friendly Upgrade", 17500000, multiplyAutomationIncome("noviceDomainU5", "automation-novice", 6), false, false, "A75=automation-novice;UnoviceDomainU4;"),
	new Array("noviceDomainU6", "Novice Respected Upgrade", 20000000, multiplyAutomationIncome("noviceDomainU6", "automation-novice", 7), false, false, "A100=automation-novice;UnoviceDomainU5;"),
	new Array("noviceDomainU7", "Novice Honoured Upgrade", 42500000, multiplyAutomationIncome("noviceDomainU7", "automation-novice", 10), false, false, "A150=automation-novice;UnoviceDomainU6;"),
	new Array("intermediateDomainU1", "Intermediate Hostile Upgrade", 10000000, multiplyAutomationIncome("intermediateDomainU1", "automation-intermediate", 2), false, false, "A1=automation-intermediate;UintermediateDomain;"),
	new Array("intermediateDomainU2", "Intermediate Angered Upgrade", 12500000, multiplyAutomationIncome("intermediateDomainU2", "automation-intermediate", 3), false, false, "A10=automation-intermediate;UintermediateDomainU1;"),
	new Array("intermediateDomainU3", "Intermediate Wary Upgrade", 15000000, multiplyAutomationIncome("intermediateDomainU3", "automation-intermediate", 4), false, false, "A25=automation-intermediate;UintermediateDomainU2;"),
	new Array("intermediateDomainU4", "Intermediate Neutral Upgrade", 17500000, multiplyAutomationIncome("intermediateDomainU4", "automation-intermediate", 5), false, false, "A50=automation-intermediate;UintermediateDomainU3;"),
	new Array("intermediateDomainU5", "Intermediate Friendly Upgrade", 20000000, multiplyAutomationIncome("intermediateDomainU5", "automation-intermediate", 6), false, false, "A75=automation-intermediate;UintermediateDomainU4;"),
	new Array("intermediateDomainU6", "Intermediate Respected Upgrade", 22500000, multiplyAutomationIncome("intermediateDomainU6", "automation-intermediate", 7), false, false, "A100=automation-intermediate;UintermediateDomainU5;"),
	new Array("intermediateDomainU7", "Intermediate Honoured Upgrade", 45000000, multiplyAutomationIncome("intermediateDomainU7", "automation-intermediate", 10), false, false, "A150=automation-intermediate;UintermediateDomainU6;"),
	new Array("advancedDomainU1", "Advanced Hostile Upgrade", 12500000, multiplyAutomationIncome("advancedDomainU1", "automation-advanced", 2), false, false, "A1=automation-advanced;UadvancedDomain;"),
	new Array("advancedDomainU2", "Advanced Angered Upgrade", 15000000, multiplyAutomationIncome("advancedDomainU2", "automation-advanced", 3), false, false, "A10=automation-advanced;UadvancedDomainU1;"),
	new Array("advancedDomainU3", "Advanced Wary Upgrade", 17500000, multiplyAutomationIncome("advancedDomainU3", "automation-advanced", 4), false, false, "A25=automation-advanced;UadvancedDomainU2;"),
	new Array("advancedDomainU4", "Advanced Neutral Upgrade", 20000000, multiplyAutomationIncome("advancedDomainU4", "automation-advanced", 5), false, false, "A50=automation-advanced;UadvancedDomainU3;"),
	new Array("advancedDomainU5", "Advanced Friendly Upgrade", 22500000, multiplyAutomationIncome("advancedDomainU5", "automation-advanced", 6), false, false, "A75=automation-advanced;UadvancedDomainU4;"),
	new Array("advancedDomainU6", "Advanced Respected Upgrade", 25000000, multiplyAutomationIncome("advancedDomainU6", "automation-advanced", 7), false, false, "A100=automation-advanced;UadvancedDomainU5;"),
	new Array("advancedDomainU7", "Advanced Honoured Upgrade", 47500000, multiplyAutomationIncome("advancedDomainU7", "automation-advanced", 10), false, false, "A150=automation-advanced;UadvancedDomainU6;"),
	new Array("expertDomainU1", "Expert Hostile Upgrade", 15000000, multiplyAutomationIncome("expertDomainU1", "automation-expert", 2), false, false, "A1=automation-expert;UexpertDomain;"),
	new Array("expertDomainU2", "Expert Angered Upgrade", 17500000, multiplyAutomationIncome("expertDomainU2", "automation-expert", 4), false, false, "A10=automation-expert;UexpertDomainU1;"),
	new Array("expertDomainU3", "Expert Wary Upgrade", 20000000, multiplyAutomationIncome("expertDomainU3", "automation-expert", 6), false, false, "A25=automation-expert;UexpertDomainU2;"),
	new Array("expertDomainU4", "Expert Neutral Upgrade", 22500000, multiplyAutomationIncome("expertDomainU4", "automation-expert", 8), false, false, "A50=automation-expert;UexpertDomainU3;"),
	new Array("expertDomainU5", "Expert Friendly Upgrade", 25000000, multiplyAutomationIncome("expertDomainU5", "automation-expert", 10), false, false, "A75=automation-expert;UexpertDomainU4;"),
	new Array("expertDomainU6", "Expert Respected Upgrade", 27500000, multiplyAutomationIncome("expertDomainU6", "automation-expert", 12), false, false, "A100=automation-expert;UexpertDomainU5;"),
	new Array("expertDomainU7", "Expert Honoured Upgrade", 50000000, multiplyAutomationIncome("expertDomainU7", "automation-expert", 15), false, false, "A150=automation-expert;UexpertDomainU6;"),
	new Array("unlockHostileAutomation", "Hostile Automation", 100000000, unlockAutomation("unlockHostileAutomation", "automation-hostile"), false, false, "UbasicDomainU1,noviceDomainU1,intermediateDomainU1,advancedDomainU1,expertDomainU1;"),
	new Array("unlockAngeredAutomation", "Angered Automation", 125000000, unlockAutomation("unlockAngeredAutomation", "automation-angered"), false, false, "A5=automation-hostile;UbasicDomainU2,noviceDomainU2,intermediateDomainU2,advancedDomainU2,expertDomainU2;"),
	new Array("unlockWaryAutomation", "Wary Automation", 150000000, unlockAutomation("unlockWaryAutomation", "automation-wary"), false, false, "A5=automation-angered;UbasicDomainU3,noviceDomainU3,intermediateDomainU3,advancedDomainU3,expertDomainU3;"),
	new Array("unlockNeutralAutomation", "Neutral Automation", 175000000, unlockAutomation("unlockNeutralAutomation", "automation-neutral"), false, false, "A5=automation-wary;UbasicDomainU4,noviceDomainU4,intermediateDomainU4,advancedDomainU4,expertDomainU4;"),
	new Array("unlockFriendlyAutomation", "Friendly Automation", 200000000, unlockAutomation("unlockFriendlyAutomation", "automation-friendly"), false, false, "A5=automation-neutral;UbasicDomainU5,noviceDomainU5,intermediateDomainU5,advancedDomainU5,expertDomainU5;"),
	new Array("unlockRespectedAutomation", "Respected Automation", 225000000, unlockAutomation("unlockRespectedAutomation", "automation-respected"), false, false, "A5=automation-friendly;UbasicDomainU6,noviceDomainU6,intermediateDomainU6,advancedDomainU6,expertDomainU6;"),
	new Array("unlockHonouredAutomation", "Honoured Automation", 250000000, unlockAutomation("unlockHonouredAutomation", "automation-honoured"), false, false, "A5=automation-respected;UbasicDomainU7,noviceDomainU7,intermediateDomainU7,advancedDomainU7,expertDomainU7;"),
	new Array("upgradeMPCU6", "Hostile MPC", 50000000, upgradeClickMPC("upgradeMPCU6", .5), false, false, "A1=automation-hostile;UupgradeMPCU5;"),
	new Array("upgradeMPCU7", "Angered MPC", 100000000, upgradeClickMPC("upgradeMPCU7", .5), false, false, "A1=automation-angered;UupgradeMCPU6;"),
	new Array("upgradeMPCU8", "Wary MPC", 150000000, upgradeClickMPC("upgradeMPCU8", .5), false, false, "A1=automation-wary;UupgradeMPCU7;"),
	new Array("upgradeMPCU9", "Neutral MPC", 250000000, upgradeClickMPC("upgradeMPCU9", .5), false, false, "A1=automation-neutral;UupgradeMCPU8;"),
	new Array("upgradeMPCU10", "Friendly MPC", 300000000, upgradeClickMPC("upgradeMPCU10", .5), false, false, "A1=automation-friendly;UupgradeMCPU8;"),
	new Array("upgradeMPCU11", "Respected MPC", 350000000, upgradeClickMPC("upgradeMPCU11", .5), false, false, "A1=automation-respected;UupgradeMCPU8;"),
	new Array("upgradeMPCU12", "Honoured MPC", 50000000, upgradeClickMPC("upgradeMPCU12", 1.5), false, false, "A1=automation-honoured;UupgradeMCPU8;"),
	new Array("hostileAutomationU1", "Basic Hostile Automation Upgrade", 5000000, upgradeAutomation("hostileAutomationU1", "automation-hostile", 100), false, false, "A10=automation-hostile;"),
	new Array("hostileAutomationU2", "Novice Hostile Automation Upgrade", 20000000, upgradeAutomation("hostileAutomationU2", "automation-hostile", 200), false, false, "A20=automation-hostile;UhostileAutomationU1;"),
	new Array("hostileAutomationU3", "Intermediate Hostile Automation Upgrade", 40000000, upgradeAutomation("hostileAutomationU3", "automation-hostile", 400), false, false, "A30=automation-hostile;UhostileAutomationU2;"),
	new Array("hostileAutomationU4", "Advanced Hostile Automation Upgrade", 120000000, upgradeAutomation("hostileAutomationU4", "automation-hostile", 800), false, false, "A40=automation-hostile;UhostileAutomationU3;"),
	new Array("hostileAutomationU5", "Expert Hostile Automation Upgrade", 360000000, upgradeAutomation("hostileAutomationU5", "automation-hostile", 1600), false, false, "A50=automation-hostile;UhostileAutomationU4;"),
	new Array("angeredAutomationU1", "Basic Angered Automation Upgrade", 6250000, upgradeAutomation("angeredAutomationU1", "automation-angered", 200), false, false, "A10=automation-angered;"),
	new Array("angeredAutomationU2", "Novice Angered Automation Upgrade", 250000000, upgradeAutomation("angeredAutomationU2", "automation-angered", 400), false, false, "A20=automation-angered;UangeredAutomationU1;"),
	new Array("angeredAutomationU3", "Intermediate Angered Automation Upgrade", 750000000, upgradeAutomation("angeredAutomationU3", "automation-angered", 800), false, false, "A30=automation-angered;UangeredAutomationU2;"),
	new Array("angeredAutomationU4", "Advanced Angered Automation Upgrade", 2250000000, upgradeAutomation("angeredAutomationU4", "automation-angered", 1600), false, false, "A40=automation-angered;UangeredAutomationU3;"),
	new Array("angeredAutomationU5", "Expert Angered Automation Upgrade", 6750000000, upgradeAutomation("angeredAutomationU5", "automation-angered", 3200), false, false, "A50=automation-angered;UangeredAutomationU4;"),
	new Array("waryAutomationU1", "Basic Wary Automation Upgrade", 75000000, upgradeAutomation("waryAutomationU1", "automation-wary", 300), false, false, "A10=automation-wary;"),
	new Array("waryAutomationU2", "Novice Wary Automation Upgrade", 300000000, upgradeAutomation("waryAutomationU2", "automation-wary", 600), false, false, "A20=automation-wary;UwaryAutomationU1;"),
	new Array("waryAutomationU3", "Intermediate Wary Automation Upgrade", 900000000, upgradeAutomation("waryAutomationU3", "automation-wary", 1200), false, false, "A30=automation-wary;UwaryAutomationU2;"),
	new Array("waryAutomationU4", "Advanced Wary Automation Upgrade", 2700000000, upgradeAutomation("waryAutomationU4", "automation-wary", 2400), false, false, "A40=automation-wary;UwaryAutomationU3;"),
	new Array("waryAutomationU5", "Expert Wary Automation Upgrade", 8100000000, upgradeAutomation("waryAutomationU5", "automation-wary", 4800), false, false, "A50=automation-wary;UwaryAutomationU4;"),
	new Array("neutralAutomationU1", "Basic Neutral Automation Upgrade", 87500000, upgradeAutomation("neutralAutomationU1", "automation-neutral", 600), false, false, "A10=automation-neutral;"),
	new Array("neutralAutomationU2", "Novice Neutral Automation Upgrade", 350000000, upgradeAutomation("neutralAutomationU2", "automation-neutral", 2400), false, false, "A20=automation-neutral;UneutralAutomationU1;"),
	new Array("neutralAutomationU3", "Intermediate Neutral Automation Upgrade", 1050000000, upgradeAutomation("neutralAutomationU3", "automation-neutral", 9600), false, false, "A30=automation-neutral;UneutralAutomationU2;"),
	new Array("neutralAutomationU4", "Advanced Neutral Automation Upgrade", 3150000000, upgradeAutomation("neutralAutomationU4", "automation-neutral", 38400), false, false, "A40=automation-neutral;UneutralAutomationU3;"),
	new Array("neutralAutomationU5", "Expert Neutral Automation Upgrade", 9450000000, upgradeAutomation("neutralAutomationU5", "automation-neutral", 153600), false, false, "A50=automation-neutral;UneutralAutomationU4;"),
	new Array("friendlyAutomationU1", "Basic Friendly Automation Upgrade", 100000000, upgradeAutomation("friendlyAutomationU1", "automation-friendly", 400), false, false, "A10=automation-friendly;"),
	new Array("friendlyAutomationU2", "Novice Friendly Automation Upgrade", 400000000, upgradeAutomation("friendlyAutomationU2", "automation-friendly", 800), false, false, "A20=automation-friendly;UfriendlyAutomationU1;"),
	new Array("friendlyAutomationU3", "Intermediate Friendly Automation Upgrade", 1200000000, upgradeAutomation("friendlyAutomationU3", "automation-friendly", 1600), false, false, "A30=automation-friendly;UfriendlyAutomationU2;"),
	new Array("friendlyAutomationU4", "Advanced Friendly Automation Upgrade", 3600000000, upgradeAutomation("friendlyAutomationU4", "automation-friendly", 3200), false, false, "A40=automation-friendly;UfriendlyAutomationU3;"),
	new Array("friendlyAutomationU5", "Expert Friendly Automation Upgrade", 10800000000, upgradeAutomation("friendlyAutomationU5", "automation-friendly", 6400), false, false, "A50=automation-friendly;UfriendlyAutomationU4;"), 
	new Array("respectedAutomationU1", "Basic Respected Automation Upgrade", 112500000, upgradeAutomation("respectedAutomationU1", "automation-respected", 500), false, false, "A10=automation-respected;"),
	new Array("respectedAutomationU2", "Novice Respected Automation Upgrade", 450000000, upgradeAutomation("respectedAutomationU2", "automation-respected", 1000), false, false, "A20=automation-respected;UrespectedAutomationU1;"),
	new Array("respectedAutomationU3", "Intermediate Respected Automation Upgrade", 1350000000, upgradeAutomation("respectedAutomationU3", "automation-respected", 2000), false, false, "A30=automation-respected;UrespectedAutomationU2;"),
	new Array("respectedAutomationU4", "Advanced Respected Automation Upgrade", 4050000000, upgradeAutomation("respectedAutomationU4", "automation-respected", 4000), false, false, "A40=automation-respected;UrespectedAutomationU3;"),
	new Array("respectedAutomationU5", "Expert Respected Automation Upgrade", 12150000000, upgradeAutomation("respectedAutomationU5", "automation-respected", 8000), false, false, "A50=automation-respected;UrespectedAutomationU4;"),
	new Array("honouredAutomationU1", "Basic Honoured Automation Upgrade", 125000000, upgradeAutomation("honouredAutomationU1", "automation-honoured", 500), false, false, "A10=automation-honoured;"),
	new Array("honouredAutomationU2", "Novice Honoured Automation Upgrade", 500000000, upgradeAutomation("honouredAutomationU2", "automation-honoured", 1000), false, false, "A20=automation-honoured;UhonouredAutomationU1;"),
	new Array("honouredAutomationU3", "Intermediate Honoured Automation Upgrade", 1500000000, upgradeAutomation("honouredAutomationU3", "automation-honoured", 2000), false, false, "A30=automation-honoured;UhonouredAutomationU2;"),
	new Array("honouredAutomationU4", "Advanced Honoured Automation Upgrade", 4500000000, upgradeAutomation("honouredAutomationU4", "automation-honoured", 4000), false, false, "A40=automation-honoured;UhonouredAutomationU3;"),
	new Array("honouredAutomationU5", "Expert Honoured Automation Upgrade", 13500000000, upgradeAutomation("honouredAutomationU5", "automation-honoured", 8000), false, false, "A50=automation-honoured;UhonouredAutomationU4;"),
	new Array("cpsU1", "Hostile CPS", 50000000000, upgradeCPS("cpsU1", .5), false, false, "A50=automation-hostile;"),
	new Array("cpsU2", "Super Hostile CPS", 75000000000, upgradeCPS("cpsU2", .5), false, false, "A100=automation-hostile;"),
	new Array("cpsU3", "Angered CPS", 75000000000, upgradeCPS("cpsU3", .5), false, false, "A50=automation-angered;"),
	new Array("cpsU4", "Super Angered CPS", 100000000000, upgradeCPS("cpsU4", .5), false, false, "A100=automation-angered;"),
	new Array("cpsU5", "Wary CPS", 100000000000, upgradeCPS("cpsU5", .5), false, false, "A50=automation-wary;"),
	new Array("cpsU6", "Super Wary CPS", 125000000000, upgradeCPS("cpsU6", .5), false, false, "A100=automation-wary;"),
	new Array("cpsU7", "Neutral CPS", 125000000000, upgradeCPS("cpsU7", .25), false, false, "A50=automation-neutral;"),
	new Array("cpsU8", "Super Neutral CPS", 150000000000, upgradeCPS("cpsU8", .25), false, false, "A100=automation-neutral;"),
	new Array("cpsU9", "Friendly CPS", 150000000000, upgradeCPS("cpsU9", .5), false, false, "A50=automation-friendly;"),
	new Array("cpsU10", "Super Friendly CPS", 175000000000, upgradeCPS("cpsU10", .5), false, false, "A100=automation-friendly;"),
	new Array("cpsU11", "Respected CPS", 200000000000, upgradeCPS("cpsU11", .5), false, false, "A50=automation-respected;"),
	new Array("cpsU12", "Super Respected CPS", 225000000000, upgradeCPS("cpsU12", .5), false, false, "A100=automation-respected;"),
	new Array("cpsU13", "Honoured CPS", 250000000000, upgradeCPS("cpsU13", 1.5), false, false, "A50=automation-honoured;"),
	new Array("cpsU14", "Super Honoured CPS", 300000000000, upgradeCPS("cpsU14", 2.0), false, false, "A100=automation-honoured;")
); // THIS FUCKING ARRAY HAS GOTTEN OUT OF HAND. I LOVE IT.
var addedBar = false; // THIS IS THAT VARIABLE FROM ./upgrades/upgradeHandler.js