var images = "./assets/images/";
// idek why I have this file...
var awardImage = "./assets/images/sprites/misc/award.png";
var buttons = new Array(images + "buttons/arrow_normal.png",
						images + "buttons/arrow_hover.png");
// seriously, what's the point of it...